### PR TITLE
3 channel data

### PR DESCRIPTION
**Pull request by Sinha-Raunak**
- Fixed bugs for compatibility with 3 channel data
- dataset2.p (converted cifar-10 (without lables))

### CODE REVIEW

**Comment by kmsenthil** [comment]
@goodboyanush can you please review this pull request.

**Comment by Sinha-Raunak** [comment]
Removed extra comments.
Please check and let me know is something needs to be further removed.

**Comment by panwarnaveen9** [comment]
> Removed extra comments.
> Please check and let me know is something needs to be further removed.

Cool.. Will check

**Comment by goodboyanush** [comment]
@panwarnaveen9 I have reviewed the new code. you can go ahead and merged it

**Pull request merged**
